on: ["pull_request"]

name: Test Pull Request

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Install Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: npm install, npm run test:cov
      run: |
        npm install
        npm run test:cov

    - name: Coveralls
      uses: coverallsapp/github-action@v2
